# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:TechORG-AgentPool

steps:
- task: TerraformInstaller@0
  displayName: Terraform Install
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'TechORG_SC'
    backendAzureRmResourceGroupName: 'aon-rg'
    backendAzureRmStorageAccountName: 'aonsa5'
    backendAzureRmContainerName: 'dep'
    backendAzureRmKey: 'dep.tfstate'


- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'


- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'


- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'TechORG_SC'