trigger: none

pool: TechORG-AgentPool

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'


- task: TerraformTask@5
  displayName: Terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'TechORG_SC'
    backendAzureRmResourceGroupName: 'aon-rg2'
    backendAzureRmStorageAccountName: 'aonsa2'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'techorg.tfstate'

- task: TerraformTask@5
  displayName: Terraform validate
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTask@5
  displayName: Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'TechORG_SC'
  timeoutInMinutes: 30