trigger: none


pool: Trifni

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'TrifniSC'
    backendAzureRmStorageAccountName: 'trifnisa'
    backendAzureRmContainerName: 'Terraform'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  displayName: Terraform validate
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTask@5
  displayName: terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'TrifniSC'
